### ISSUE TITLE
Libraries and errors

### ISSUE THREAD

**Issue by palmtreefrb** [kevinkk525/pysmartnode#16]
I'm having questions and issues.

- Following your instructions, copy(flash) "pysmartnode" directory after updating the submodules.
  Are the libraries and associated readme, license and image files required?

- The networking/mqtt.py is importing class **Lock** however it is not contained in the mqtt_as.py file or any other library contained in your project after updating submodules. 
  **from micropython_mqtt_as.mqtt_as import MQTTClient, Lock** 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "pysmartnode/main.py", line 12, in <module>
  File "pysmartnode/config.py", line 54, in <module>
  File "pysmartnode/networking/mqtt.py", line 20, in <module>
ImportError: cannot import name Lock

**Comment by kevinkk525** [comment]
Oh yeah, I'm in the process of porting all libraries to the new uasynio version that is present in the daily builds of micropython. Please use the "uasyncio_next" branch of pysmartnode. 

It is not advised to just copy the pysmartnode directory to the flash because the device would then need to compile every py file which will need huge amounts of ram.
See the tools section for Esp32 for how to create mpy files that you can sync onto your device.

Also not that just copying the .py files won't work because of:

> modules use Variable Annotations ([PEP526](https://www.python.org/dev/peps/pep-0526/)) but micropython doesn't support
[PEP 526 (Syntax for Variable Annotations)](https://github.com/micropython/micropython/issues/2415#issuecomment-548173512) yet.
This means that every build, .mpy or directly uploaded file with variable annotations will fail.
To work around this problem, the files have to be stripped of their variable annotations. This can be done with the python module "strip-hints".  (see tools directory for examples)

Generally only the .py or .mpy files are required on the device.

**Comment by palmtreefrb** [comment]
Ok thanks, one more question. I saw the notes on strip-hints. I'm using esp32 and I did not see a script for esp32 only for esp8266 "esp8266_remove_hints.sh"

**Comment by kevinkk525** [comment]
Ah I see, it is hidden in https://github.com/kevinkk525/pysmartnode/blob/uasyncio_next/tools/esp32/ftp/generate_bytecode.sh which does both, strip hints and generate the mpy files.

I also just made a beta release for the new uasyncio version with the .mpy files, maybe that is easier: https://github.com/kevinkk525/pysmartnode/releases/tag/v6.1.0

**Comment by palmtreefrb** [comment]
Wow, that's fast. Thanks...
I build micropython frequently, but during development I find it easier to have code un-frozen. Is strip-hints required for flashing files to device?

**Comment by kevinkk525** [comment]
yes strip-hints is required because some modules use PEP526 annotations that will throw an error when micropython compiles them.
So if you want to use the .py files, you will have to run strip-hints over all files. You can still use the esp32 generate_bytecode.sh and just comment out the line that generates .mpy files.
