### ISSUE TITLE
esp32 wdt

### ISSUE THREAD

**Issue by palmtreefrb** [kevinkk525/pysmartnode#19]
Can your implementation watchdog.py component be used for esp32?

**Comment by kevinkk525** [comment]
Well it should work. But there is actually no point in using it with the esp32 because it is a software watchdog implementation using Timers. It was useful on the esp8266 due to a bug in the micropython firmware which has been fixed a long time ago. I don't think I've ever seen an esp8266 be reset by the watchdog since then but I kept it, just to be sure.
The esp32 has a hardware watchdog and I've seen that one resetting my boards occasionally so I don't think there's any benefit in using an additional software watchdog on the esp32.
